In [ ]:
import numpy as np
import random

# Classes

In [ ]:
class ExtendedHammingCode:
  def RandomMessage():
    m = np.random.randint(2,size=(4,1))
    return m

  def GeneratorMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1],
             [1,1,1,1]])
    return G

  def DualGeneratorMatrix():
    H = np.array([[1,1,0,1,1,0,0,0],
             [1,0,1,1,0,1,0,0],
             [0,1,1,1,0,0,1,0],
             [1,1,1,1,0,0,0,1]])
    G = H.T
    return G

  def ParityCheckMatrix():
    H = np.array([[1,1,0,1,1,0,0,0],
             [1,0,1,1,0,1,0,0],
             [0,1,1,1,0,0,1,0],
             [1,1,1,1,0,0,0,1]])
    return H

  def DualParityCheckMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1],
             [1,1,1,1]])
    H = G.T
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_8 = np.identity(8, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, np.swapaxes(H[:, i][np.newaxis],0,1))):
        e_i = np.swapaxes(I_8[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[0],CA[1],CA[2],CA[3]])
    return m

In [ ]:
G = ExtendedHammingCode.GeneratorMatrix()
H = ExtendedHammingCode.ParityCheckMatrix()

m = ExtendedHammingCode.RandomMessage()
print("message:")
print(m)

CA = ExtendedHammingCode.encode(m, G)
print("encoding:")
print(CA)
e = np.array([[1],[0],[0],[0],[0],[0],[0],[0]]) # change to test for diff errors
CB = ExtendedHammingCode.send(CA, e)
print("transmission:")
print(CB)

syndrome = ExtendedHammingCode.check(CB, H)
print("syndrome:")
print(syndrome)
m = ExtendedHammingCode.decode(CB, H)
print("output:")
print(m)

message:
[[0]
 [1]
 [1]
 [1]]
encoding:
[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]]
transmission:
[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]]
syndrome:
[[1]
 [1]
 [0]
 [1]]
output:
[[0]
 [1]
 [1]
 [1]]
