In [81]:
import numpy as np
import random

# Classes

In [87]:
class HammingCode:
  def RandomMessage():
    m = np.random.randint(2,size=(4,1))
    return m

  def GeneratorMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1]])
    return G

  def ParityCheckMatrix():
    H = np.array([[1,1,0,1,1,0,0],
             [1,0,1,1,0,1,0],
             [0,1,1,1,0,0,1]])
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_7 = np.identity(7, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, np.swapaxes(H[:, i][np.newaxis],0,1))):
        e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[0],CA[1],CA[2],CA[3]])
    return m

# Testing Classes

In [88]:
G = HammingCode.GeneratorMatrix()
H = HammingCode.ParityCheckMatrix()

m = HammingCode.RandomMessage()
print("message:")
print(m)

CA = HammingCode.encode(m, G)
print("encoding:")
print(CA)
e = np.array([[1],[0],[0],[0],[0],[0],[0]]) # change to test for diff errors
CB = HammingCode.send(CA, e)
print("transmission:")
print(CB)

syndrome = HammingCode.check(CB, H)
print("syndrome:")
print(syndrome)
m = HammingCode.decode(CB, H)
print("output:")
print(m)

message:
[[0]
 [0]
 [1]
 [1]]
encoding:
[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]
transmission:
[[1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]
syndrome:
[[1]
 [1]
 [0]]
output:
[[0]
 [0]
 [1]
 [1]]
