In [156]:
import numpy as np

In [157]:
m = np.random.randint(2,size=(4,1))
print(m)

[[1]
 [0]
 [1]
 [0]]


# Encoding

In [158]:
H = np.array([[1,1,1,0,1,0,0],
             [1,1,0,1,0,1,0],
             [1,0,1,1,0,0,1]])
G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,1,0],
             [1,1,0,1],
             [1,0,1,1]])
CA = (G @ m) % 2
print(CA)


[[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]]


# Sending

In [159]:
e = np.array([[1],[0],[0],[0],[0],[0],[0]])
CB = (CA + e) % 2
print(CB)

[[0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]]


# Check and Correct

In [160]:
syndrome = (H @ CB) % 2
I_7 = np.identity(7, dtype=np.int8)
e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
for i in range(7):
  if(np.array_equiv((H @ CB) % 2, H[:, i])):
    e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
CA = (CB + e_i) % 2
print(CA)

[[1]
 [1]
 [1]]
[[1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]]


# Decode

In [161]:
m = np.array([CA[0],CA[1],CA[2],CA[3]])
print(m)

[[1]
 [0]
 [1]
 [0]]


# Classes

In [162]:
class HammingCode:

  def GeneratorMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,1,0],
             [1,1,0,1],
             [1,0,1,1]])
    return G

  def ParityCheckMatrix():
    H = np.array([[1,1,1,0,1,0,0],
             [1,1,0,1,0,1,0],
             [1,0,1,1,0,0,1]])
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    e = np.array([[1],[0],[0],[0],[0],[0],[0]])
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_7 = np.identity(7, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, H[:, i])):
        e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[0],CA[1],CA[2],CA[3]])
    return m