In [118]:
import numpy as np

In [119]:
m = np.random.randint(2,size=(4,1))
print(m)

[[1]
 [1]
 [1]
 [0]]


# Encoding

In [120]:
H = np.array([[1,1,0,1,1,0,0],
             [1,0,1,1,0,1,0],
             [0,1,1,1,0,0,1]])
G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1]])
CA = (G @ m) % 2
print(CA)


[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


# Sending

In [121]:
e = np.array([[1],[0],[0],[0],[0],[0],[0]])
CB = (CA + e) % 2
print(CB)

[[0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


# Check and Correct

In [122]:
syndrome = (H @ CB) % 2
print(syndrome)
I_7 = np.identity(7, dtype=np.int8)
e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
for i in range(7):
  if(np.array_equiv((H @ CB) % 2, np.swapaxes(H[:, i][np.newaxis],0,1))):
    e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
CA = (CB + e_i) % 2
print(CA)

[[1]
 [1]
 [0]]
[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


# Decode

In [123]:
m = np.array([CA[0],CA[1],CA[2],CA[3]])
print(m)

[[1]
 [1]
 [1]
 [0]]


# Classes

In [124]:
class HammingCode:

  def GeneratorMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1]])
    return G

  def ParityCheckMatrix():
    H = np.array([[1,1,0,1,1,0,0],
             [1,0,1,1,0,1,0],
             [0,1,1,1,0,0,1]])
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_7 = np.identity(7, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, np.swapaxes(H[:, i][np.newaxis],0,1))):
        e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[0],CA[1],CA[2],CA[3]])
    return m

# Testing Classes

In [125]:
G = HammingCode.GeneratorMatrix()
H = HammingCode.ParityCheckMatrix()

m = np.random.randint(2,size=(4,1))
print(m)

CA = HammingCode.encode(m, G)
print(CA)
e = np.array([[1],[0],[0],[0],[0],[0],[0]])
CB = HammingCode.send(CA, e)
print(CB)

syndrome = HammingCode.check(CB, H)
print(syndrome)
m = HammingCode.decode(CB, H)
print(m)

[[0]
 [0]
 [1]
 [1]]
[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]
[[1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]]
[[1]
 [1]
 [0]]
[[0]
 [0]
 [1]
 [1]]
