In [97]:
import numpy as np
import random

# Classes

In [103]:
class RepetitionCode:
  def RandomMessage():
    databit = np.random.randint(2,size=(1,1))
    return databit

  def GeneratorMatrix(n):
    G = np.ones([n,1], dtype=np.int8)
    return G

  def ParityCheckMatrix(n):
    I = np.identity(n-1, dtype=np.int8)
    ones = np.ones([n-1,1], dtype=np.int8)
    H = np.concatenate((ones, I), axis=1)
    return H

  def encode(databit, G):
    codeword = G @ databit
    return codeword

  def send(codeword, error):
    erronousword = (codeword + error) % 2
    return erronousword

  def check(erronousword, H):
    syndrome = (H @ erronousword) % 2
    return syndrome

  def decode(erronousword, n):
    majority = np.sum(erronousword)
    if(majority >= n/2):
      result = 1
    else:
      result = 0
    return result

# Testing Classes

In [104]:
n = 3 # change for different size repetition codes
G = RepetitionCode.GeneratorMatrix(n)
H = RepetitionCode.ParityCheckMatrix(n)

m = RepetitionCode.RandomMessage()
print("message:")
print(m)

CA = RepetitionCode.encode(m, G)
print("encoding:")
print(CA)
e = np.array([[1],[0],[0]]) # change to test for diff errors
CB = RepetitionCode.send(CA, e)
print("transmission:")
print(CB)

syndrome = RepetitionCode.check(CB, H)
print("syndrome:")
print(syndrome)
m = RepetitionCode.decode(CB, n)
print("output:")
print(m)

message:
[[1]]
encoding:
[[1]
 [1]
 [1]]
transmission:
[[0]
 [1]
 [1]]
syndrome:
[[1]
 [1]]
output:
1
