In [ ]:
import numpy as np

In [14]:
class SimplexCode:
  def RandomMessage():
    m = np.random.randint(2,size=(3,1))
    return m

  def GeneratorMatrix():

    H = np.array([[1,1,0,1,1,0,0],
             [1,0,1,1,0,1,0],
             [0,1,1,1,0,0,1]])
    G = H.T
    return G

  def ParityCheckMatrix():
    G = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [0,0,0,1],
             [1,1,0,1],
             [1,0,1,1],
             [0,1,1,1]])
    H = G.T
    return H

  def encode(m, G):
    CA = (G @ m) % 2
    return CA

  def send(CA, e):
    CB = (CA + e) % 2
    return CB

  def check(CB, H):
    syndrome = (H @ CB) % 2
    return syndrome

  def decode(CB, H):
    I_7 = np.identity(7, dtype=np.int8)
    e_i = np.array([[0],[0],[0],[0],[0],[0],[0]])
    for i in range(7):
      if(np.array_equiv((H @ CB) % 2, np.swapaxes(H[:, i][np.newaxis],0,1))):
        e_i = np.swapaxes(I_7[np.newaxis,i],0,1)
    CA = (CB + e_i) % 2
    m = np.array([CA[4],CA[5],CA[6]])
    return m

# Testing Classes

In [15]:
G = SimplexCode.GeneratorMatrix()
H = SimplexCode.ParityCheckMatrix()

m = SimplexCode.RandomMessage()
print("message:")
print(m)

CA = SimplexCode.encode(m, G)
print("encoding:")
print(CA)
e = np.array([[1],[0],[0],[0],[0],[0],[0]]) # change to test for diff errors
CB = SimplexCode.send(CA, e)
print("transmission:")
print(CB)

syndrome = SimplexCode.check(CB, H)
print("syndrome:")
print(syndrome)
m = SimplexCode.decode(CB, H)
print("output:")
print(m)

message:
[[1]
 [1]
 [0]]
encoding:
[[0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]]
transmission:
[[1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]]
syndrome:
[[1]
 [0]
 [0]
 [0]]
output:
[[1]
 [1]
 [0]]
